export const urls = {
    'LOGIN_URL': '/login',
    'REGISTER_URL': '/register',
    'FORGOT_PASSWORD_URL': '/forgot-password',
    'RESET_PASSWORD_URL': '/reset-password',
    'VERIFY_EMAIL_URL': '/verify-email',
    'SETUP_ACCOUNT': '/setup-account',
    'ALL_ROOM': "/all-room",
    'GET_ROOM': '/room',
    'ADD_ROOM': '/add-room',
    'REQUEST_ROOM': '/request-email',
    'DELETE_ROOM': "/delete-room",
    'GET_USER': '/user',
    'GET_OWNER': '/owner',
    'GET_POTENTIAL_MATCHES': '/match',
    'GET_ACCEPTED_MATCHES': '/get-accepted-requests',
    'GET_REQUESTED_MATCHES': '/get-pending-requests',
    'ACCEPT_REQUEST': '/accept-request',
    'DECLINE_REQUEST': '/decline-request',
    'SEND_REQUEST': '/new-request',
};