export const urls = {
    'LOGIN_URL': '/login',
    'REGISTER_URL': '/register',
    'FORGOT_PASSWORD_URL': '/forgot-password',
    'RESET_PASSWORD_URL': '/reset-password',
    'VERIFY_EMAIL_URL': '/verify-email',
    'SETUP_ACCOUNT': '/setup-account',
    'ALL_ROOM': "/all-room",
    'GET_ROOM': '/room',
    'ADD_ROOM': '/add-room',
    'REQUEST_ROOM': '/request-email',
    'DELETE_ROOM': "/delete-room",
    'GET_USER': '/user',
    'GET_OWNER': '/owner',
};